version: "3.9"

services:
  # server: #サービス名
  #   build:
  #     context: . #ビルドに使用するDockerfileの場所
  #     dockerfile: Dockerfile
  #   container_name: fyp-server #コンテナの名前
  #   tty: true #コンテナの永続化
  #   ports:
  #     - "8080:8080"
  #   depends_on: #依存関係
  #     - db
  #   volumes: #マウントディレクトリ
  #     - .:/app
  #     - go-data:/go

  db: #サービス名
    image: postgres:latest #ビルドに使用するimageファイル
    container_name: fyp-db #コンテナの名前
    environment:
      POSTGRES_DB: ${DB_NAME} #データベース名
      POSTGRES_PASSWORD: ${DB_PASSWORD} #データベースパスワード
      POSTGRES_USER: ${DB_USER} #データベースユーザ名
      TimeZone: ${DB_TIMEZONE} #タイムゾーン
    ports:
      - "5432:${DB_PORT}"
    volumes: #マウントディレクトリ
      - /var/lib/postgres/data

volumes:
  go-data:
