version: '3.3'

services:

  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INTITD_ROOT_USERNAME: development
      MONGO_INTITD_ROOT_PASSWORD: testpassword
