// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interfaces/auth.go
//
// Generated by this command:
//
//	mockgen -source=pkg/repository/interfaces/auth.go -destination=pkg/repository/mock/auth_mock.go
//
// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	v4 "github.com/labstack/echo/v4"
	domain "github.com/shion0625/FYP/backend/pkg/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// FindRefreshSessionByTokenID mocks base method.
func (m *MockAuthRepository) FindRefreshSessionByTokenID(ctx v4.Context, tokenID string) (domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshSessionByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshSessionByTokenID indicates an expected call of FindRefreshSessionByTokenID.
func (mr *MockAuthRepositoryMockRecorder) FindRefreshSessionByTokenID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshSessionByTokenID", reflect.TypeOf((*MockAuthRepository)(nil).FindRefreshSessionByTokenID), ctx, tokenID)
}

// SaveRefreshSession mocks base method.
func (m *MockAuthRepository) SaveRefreshSession(ctx v4.Context, refreshSession domain.RefreshSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshSession", ctx, refreshSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshSession indicates an expected call of SaveRefreshSession.
func (mr *MockAuthRepositoryMockRecorder) SaveRefreshSession(ctx, refreshSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshSession", reflect.TypeOf((*MockAuthRepository)(nil).SaveRefreshSession), ctx, refreshSession)
}
