// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/shion0625/FYP/backend/pkg/api"
)

// Injectors from wire.go:

func InitializeApi() (*http.ServerHTTP, error) {
	serverHTTP := http.NewServerHTTP()
	return serverHTTP, nil
}
