name: ecommerce-project-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Setup action
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod verify
          
      - name: Run Build
        run: go build ./cmd/api
      
      - name: Run Test
        run: |
          go test -v -cover ./...
      
      - name: Login To Docker Hub
        run: docker login -u nikhil382 -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build And Push The Docker Image
        run: |
          docker build -t nikhil382/ecommerce-gin-clean-arch .
          docker push nikhil382/ecommerce-gin-clean-arch
      

      
    
